view:
    resource: "@ViewBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:  /api
    type: rest

fallback:
    resource: "@ViewBundle/Resources/config/routing.yml"
    prefix:   /{url}
    requirements:
     url: .*