services:
    api.group_rest_controller:
        class: ApiBundle\Controller\GroupController
        arguments:
            - "@request_stack"
            - "@groupDataManager"
            
    api.file_rest_controller:
      class: ApiBundle\Controller\FileController
      arguments:
          - "@request_stack"
          - "@fileDataManager"
          
    api.language_rest_controller:
      class: ApiBundle\Controller\LanguageController
      arguments:
          - "@request_stack"
          - "@languageDataManager"      
         
